[general]
unsafe-accounts-conf = true
default-save-path = /home/aerc/mail-attachments
fuzzy-complete = true

[ui]
index-columns = date<20,name<25,flags>4,subject<*
timestamp-format = 2006-01-02 15:04
sidebar-width = 20
mouse-enabled = false
threading-enabled = true
sort = -r date
icon-unread = *
icon-flagged = !
icon-attachment = @
tab-title-account = {{.Account}}{{if .Unread}} ({{.Unread}}){{end}}
new-message-bell = true

[ui:account=archive]
index-columns = date<20,name<25,flags>4,tags<10,subject<*
column-tags = {{.Labels | join ","}}

[viewer]
pager = less -R
alternatives = text/plain,text/html
header-layout = From,To,Cc,Bcc,Subject,Date

[openers]
text/html = w3m

[templates]
template-dirs = /home/aerc/.config/aerc/templates

[compose]
editor = vim -u /home/aerc/.config/aerc/vimrc
header-layout = To,Cc,Bcc,From,Subject
address-book-cmd = sh /home/aerc/.config/aerc/scripts/addr-complete.sh '%s'

[compose:account=work]
editor = vim -u /home/aerc/.config/aerc/vimrc
reply-to-self = true
empty-subject-warning = true
no-attachment-warning = ^[^>]*attach
format-flowed = false

[filters]
text/plain = /usr/libexec/aerc/filters/colorize
text/html = w3m -I UTF-8 -T text/html -dump -o display_image=false -o display_link_number=true
text/calendar = /usr/libexec/aerc/filters/calendar
message/rfc822 = /usr/libexec/aerc/filters/colorize
application/pdf = pdftotext - -
image/* = chafa -f sixel -
